services:
  # 1. Contenedor de la Base de Datos (MySQL)
  bbdd:
    image: mysql:8.0
    container_name: tienda_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: tienda_funkos
    volumes:
      - mysql_data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "3306:3306"

  # 2. Contenedor de la aplicación Java
  java_app:
    build: .
    container_name: tienda_java
    restart: always
    tty: true           # Permite interactuar con la consola del contenedor
    stdin_open: true    # Mantiene el teclado abierto para el Scanner
    depends_on:
      - bbdd
    environment:
      - DB_URL="jdbc:mysql://bbdd:3306/tienda_funkos?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
      - DB_USER=root
      - DB_PASSWORD=toor

  # 3. Contenedor para el servidor Web (Nginx + Autenticación + SSL)
  web_html:
    image: nginx:latest
    container_name: tienda_web
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DESCARGAS_USER=user
      - DESCARGAS_PASSWORD=toor
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - certbot_certs:/etc/letsencrypt
      - certbot_www:/var/www/certbot
    command: >
      /bin/sh -c "
      apt-get update && apt-get install -y apache2-utils &&
      htpasswd -b -c /tmp/.htpasswd $$DESCARGAS_USER $$DESCARGAS_PASSWORD &&
      echo '=> Archivo .htpasswd generado con éxito en /tmp/.' &&
      nginx -g 'daemon off;'
      "

  # 4. Renovador Automático de Certificados Certbot
  certbot:
    image: certbot/certbot:latest
    container_name: tienda_certbot
    restart: always
    volumes:
      - certbot_certs:/etc/letsencrypt
      - certbot_www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot --quiet && docker kill -s HUP tienda_web; sleep 12h & wait $${!}; done'"

volumes:
  mysql_data:
  certbot_certs:
  certbot_www: