events { worker_connections 1024; }

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    # SERVIDOR HTTP: Redirige todo el tráfico a HTTPS
    server {
        listen 80;
        server_name poppai.yatat.es;

        # Ruta indispensable para que Certbot valide el dominio desde Docker
        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        location / {
            return 301 https://$host$request_uri;
        }
    }

    # SERVIDOR HTTPS: Servidor seguro con candado SSL
    server {
        listen 443 ssl;
        server_name poppai.yatat.es;

        # Rutas de los certificados SSL que generará Certbot
        ssl_certificate     /etc/letsencrypt/live/poppai.yatat.es/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/poppai.yatat.es/privkey.pem;

        # Protocolos seguros recomendados
        ssl_protocols       TLSv1.2 TLSv1.3;
        ssl_ciphers         HIGH:!aNULL:!MD5;

        # Web normal abierta a todo el mundo
        location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri $uri/ =404;
        }

        # SECCIÓN PRIVADA: Carpeta de descargas protegida con login
        location /descargas {
            root /usr/share/nginx/html;
            auth_basic "Zona Protegida - Solo Amigos";
            auth_basic_user_file /tmp/.htpasswd;
            
            autoindex on; 
        }
    }
}