events { worker_connections 1024; }

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    server {
        listen 80;
        server_name localhost; # En AWS puedes cambiarlo por tu dominio o tu IP si lo prefieres

        # Web normal abierta a todo el mundo
        location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri $uri/ =404;
        }

        # SECCIÓN PRIVADA: Carpeta de descargas protegida
        location /descargas {
            root /usr/share/nginx/html;
            auth_basic "Zona Protegida - Solo Amigos";
            auth_basic_user_file /tmp/.htpasswd; # <- Lee de la ruta temporal autogenerada
            
            autoindex on; 
        }
    }
}